### Site Settings ###
title               : ItsTiazzz
description         : >-
                      I do stuff sometimes
baseurl             : ""            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : ItsTiazzz/ItsTiazzz.github.io      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : true                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : ItsTiazzz
  image             : ./assets/images/page.png
#  behance           : your_username
# dribbble          : your_username
  email             : business@tiazzz.me
#  facebook          : your_username
  github            : ItsTiazzz
  gitlab            : TywrapStudios
# instagram         : your_username
# kaggle            : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
  twitch            : tywrapstudiosyt
#  twitter           : your_username
# vimeo             : your_username
  youtube           : channel/UC_QXVzz4DjsH-HDmJe5Yheg
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  translation-projects:
    output: true
    permalink: /translation-projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: G-4S5DF4QC1V


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "translation-projects"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
      layout: "post"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - r/
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
